name = "LatPhysReciprocal"
uuid = "7a511e88-ebe4-11e8-1bac-67d16a536c98"
authors = ["Jan Attig <jattig@thp.Uni-Koeln.DE>"]
version = "0.1.0"

[deps]
LatPhysBase = "eec5c15a-e8bd-11e8-0d23-6799ca40c963"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
